In [1]:
#!pip install degiro_connector pandas scipy sqlitedict polars yfinance unidecode pyarrow
#!pip install selenium
#!pip install --upgrade lxml
#!pip install pyportfolioopt   matplotlib seaborn

In [2]:
from screener import Screener, main
import logging
import sys
import locale
from screener import build_csv 
import os
import polars as pl
import csv
from errno import EBUSY
import json

import numpy as np
import os
import re
import polars as pl

import traceback
 
from DictObj import DictObj
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from degiro_connector.quotecast.models.chart import Interval
from degiro_connector.trading.models.credentials import build_credentials
from degiro_connector.trading.models.product_search import StocksRequest
from ranking import compute_rank, ranking 
from telegram import send_doc_to_telegram
from typing import Any, Dict, List, Optional, Set, Tuple
from utils import crapy_estimates_summaries_get
from xvfb import openWindow
import locale
from itertools import repeat

import http.client
http.client.HTTPConnection.debuglevel = 5

#pl.col(column1).str.contains(regex1, literal=False) 
pl.Config.set_tbl_rows(50)   # max rows to display
pl.Config.set_tbl_cols(500)   # max columns to display
pl.Config.set_float_precision(2)
pl.Config.set_tbl_width_chars(2000)
pl.Config.set_tbl_cell_numeric_alignment("RIGHT")

locale.setlocale(locale.LC_NUMERIC, os.getenv("LANG", "C"))
'''
for key, value in os.environ.items():
    if key.startswith("GT"):
        print(f"{key}:\t{value:.1s}***{value[-1]:.1s}")
'''

'\nfor key, value in os.environ.items():\n    if key.startswith("GT"):\n        print(f"{key}:\t{value:.1s}***{value[-1]:.1s}")\n'

In [3]:
import polars as pl
import logging
from telegram import send_doc_to_telegram
import sys

logfile = "./outdegiro.log"
logging_level = logging.DEBUG
logging.basicConfig(
    level=logging_level,
    handlers=[logging.FileHandler(logfile, mode="a"), logging.StreamHandler(sys.stdout), ],
    format="%(asctime)s - %(name)s:%(filename)s:%(funcName)s:%(lineno)d - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

df, rows = Screener(None, None, None, None, [ "MX.json"])  # "FR0000052292",  ["MX.json"] ['FR'] "JP3531800005" "KR.json", "NS BO.json", "SA.json","MX.json" "KR.json", "NS BO.json", "SA.json",
#main(None, None, None, ['PT'], None) #   'PT' "korea-sample.json"

2026-06-20 17:32:22 - root:cachedApi.py:__init__:13 - DEBUG - Initializing cache at /home/fab/Documents/simu/data/cacheYahoo.bin
2026-06-20 17:32:22 - root:cachedYahooApi.py:__init__:35 - DEBUG - set yahoo cache location "/home/fab/Documents/simu/data" <- /home/fab/Documents/simu/data/cacheYahoo.bin
2026-06-20 17:32:22 - root:cachedApi.py:open_db:17 - DEBUG - Opening DB /home/fab/Documents/simu/data/cacheYahoo.bin
2026-06-20 17:32:22 - sqlitedict:sqlitedict.py:__init__:221 - DEBUG - opening Sqlite table 'unnamed' in '/home/fab/Documents/simu/data/cacheYahoo.bin'
2026-06-20 17:32:22 - root:cachedYahooApi.py:__init__:68 - DEBUG - Yahoo setup done
2026-06-20 17:32:22 - root:cachedApi.py:__init__:13 - DEBUG - Initializing cache at /home/fab/Documents/simu/data/cacheFrankfurter.bin
2026-06-20 17:32:22 - root:cachedApi.py:open_db:17 - DEBUG - Opening DB /home/fab/Documents/simu/data/cacheFrankfurter.bin
2026-06-20 17:32:22 - sqlitedict:sqlitedict.py:__init__:221 - DEBUG - opening Sqlite table 'unnamed' in '/home/fab/Documents/simu/data/cacheFrankfurter.bin'
2026-06-20 17:32:22 - root:cachedApi.py:_cleanup_expired_entries:39 - DEBUG - DB cleanup: keeping 1 items, removed 0 items
2026-06-20 17:32:22 - root:cachedfaz.py:__init__:31 - DEBUG - frankfurter.app setup done
2026-06-20 17:32:22 - root:cachedApi.py:__init__:13 - DEBUG - Initializing cache at /home/fab/Documents/simu/data/cacheScreenerYahoo.bin
2026-06-20 17:32:22 - root:cachedYahooApi.py:__init__:35 - DEBUG - set yahoo cache location "/home/fab/Documents/simu/data" <- /home/fab/Documents/simu/data/cacheScreenerYahoo.bin
2026-06-20 17:32:22 - root:cachedApi.py:open_db:17 - DEBUG - Opening DB /home/fab/Documents/simu/data/cacheScreenerYahoo.bin
2026-06-20 17:32:22 - sqlitedict:sqlitedict.py:__init__:221 - DEBUG - opening Sqlite table 'unnamed' in '/home/fab/Documents/simu/data/cacheScreenerYahoo.bin'
2026-06-20 17:32:22 - root:cachedYahooApi.py:__init__:68 - DEBUG - Yahoo setup done
2026-06-20 17:32:22 - root:screenerYahoo.py:read_json_to_dict:252 - WARNING - Fichier 'MX.json' chargé avec succès !
2026-06-20 17:32:23 - yfinance:search.py:search:100 - DEBUG - ABBNN.MX: Yahoo GET parameters: {'q': 'ABBNN.MX', 'quotesCount': 3, 'enableFuzzyQuery': False, 'newsCount': 0, 'quotesQueryId': 'tss_match_phrase_query', 'newsQueryId': 'news_cie_vespa', 'listsCount': 8, 'enableCb': True, 'enableNavLinks': False, 'enableResearchReports': False, 'enableCulturalAssets': False, 'recommendedCount': 8}
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG - Entering get()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering _make_request()
2026-06-20 17:32:23 - yfinance:data.py:_make_request:398 - DEBUG - url=https://query2.finance.yahoo.com/v1/finance/search
2026-06-20 17:32:23 - yfinance:data.py:_make_request:399 - DEBUG - params=frozendict.frozendict({'q': 'ABBNN.MX', 'quotesCount': 3, 'enableFuzzyQuery': False, 'newsCount': 0, 'quotesQueryId': 'tss_match_phrase_query', 'newsQueryId': 'news_cie_vespa', 'listsCount': 8, 'enableCb': True, 'enableNavLinks': False, 'enableResearchReports': False, 'enableCulturalAssets': False, 'recommendedCount': 8})
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _get_cookie_and_crumb()
2026-06-20 17:32:23 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_basic()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _load_cookie_curlCffi()
2026-06-20 17:32:23 - peewee:peewee.py:execute_sql:3303 - DEBUG - ('CREATE TABLE IF NOT EXISTS "_cookieschema" ("strategy" VARCHAR(255) NOT NULL PRIMARY KEY, "fetch_date" DATETIME NOT NULL, "cookie_bytes" BLOB NOT NULL) WITHOUT ROWID', [])
2026-06-20 17:32:23 - peewee:peewee.py:execute_sql:3303 - DEBUG - ('SELECT "t1"."strategy", "t1"."fetch_date", "t1"."cookie_bytes" FROM "_cookieschema" AS "t1" WHERE ("t1"."strategy" = ?) LIMIT ? OFFSET ?', ['curlCffi', 1, 0])
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _load_cookie_curlCffi()
2026-06-20 17:32:23 - yfinance:data.py:_get_cookie_basic:193 - DEBUG - reusing persistent cookie
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_basic()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_crumb_basic()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_cookie_basic()
2026-06-20 17:32:23 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_cookie_basic()
2026-06-20 17:32:23 - yfinance:data.py:_get_crumb_basic:239 - DEBUG - crumb = '.BKxKSFvLQW'
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_crumb_basic()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _get_cookie_and_crumb()
2026-06-20 17:32:23 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting _make_request()
2026-06-20 17:32:23 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting get()
2026-06-20 17:32:23 - root:cachedYahooApi.py:ysearch:100 - DEBUG - ysearch error - ysearch2 ABBNN.MX 3 0 False
2026-06-20 17:32:23 - root:cachedYahooApi.py:product_search:170 - DEBUG - product_search yahoo None/ABBNN.MX/ABB LTD, FOUND ! -> ABB -> 'ABBNN.MX' / 'ABB LTD'
2026-06-20 17:32:23 - root:screenerYahoo.py:getAllYahoo:292 - INFO - ['MX']°ABBNN.MX°ABB LTD -> ABBNN.MX
2026-06-20 17:32:24 - yfinance:data.py:get_raw_json:461 - DEBUG - get_raw_json(): https://query2.finance.yahoo.com/v10/finance/quoteSummary/ABBNN.MX
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG - Entering get()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering _make_request()
2026-06-20 17:32:24 - yfinance:data.py:_make_request:398 - DEBUG - url=https://query2.finance.yahoo.com/v10/finance/quoteSummary/ABBNN.MX
2026-06-20 17:32:24 - yfinance:data.py:_make_request:399 - DEBUG - params={'modules': 'financialData,quoteType,defaultKeyStatistics,assetProfile,summaryDetail', 'corsDomain': 'finance.yahoo.com', 'formatted': 'false', 'symbol': 'ABBNN.MX'}
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _get_cookie_and_crumb()
2026-06-20 17:32:24 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_basic()
2026-06-20 17:32:24 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_crumb_basic()
2026-06-20 17:32:24 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _get_cookie_and_crumb()
2026-06-20 17:32:24 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting _make_request()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting get()
2026-06-20 17:32:24 - yfinance:data.py:get_raw_json:461 - DEBUG - get_raw_json(): https://query1.finance.yahoo.com/v7/finance/quote?
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG - Entering get()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering _make_request()
2026-06-20 17:32:24 - yfinance:data.py:_make_request:398 - DEBUG - url=https://query1.finance.yahoo.com/v7/finance/quote?
2026-06-20 17:32:24 - yfinance:data.py:_make_request:399 - DEBUG - params={'symbols': 'ABBNN.MX', 'formatted': 'false'}
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _get_cookie_and_crumb()
2026-06-20 17:32:24 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_basic()
2026-06-20 17:32:24 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_crumb_basic()
2026-06-20 17:32:24 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _get_cookie_and_crumb()
2026-06-20 17:32:24 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting _make_request()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting get()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG - Entering get()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering _make_request()
2026-06-20 17:32:24 - yfinance:data.py:_make_request:398 - DEBUG - url=https://query1.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/ABBNN.MX?symbol=ABBNN.MX&type=trailingPegRatio&period1=1766188800&period2=1782000000
2026-06-20 17:32:24 - yfinance:data.py:_make_request:399 - DEBUG - params=None
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _get_cookie_and_crumb()
2026-06-20 17:32:24 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_basic()
2026-06-20 17:32:24 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_crumb_basic()
2026-06-20 17:32:24 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _get_cookie_and_crumb()
2026-06-20 17:32:24 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting _make_request()
2026-06-20 17:32:24 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting get()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG - Entering _fetch_time_series()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering get()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _make_request()
2026-06-20 17:32:25 - yfinance:data.py:_make_request:396 - DEBUG - url=https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/ABBNN.MX?symbol=ABBNN.MX&type=annualTaxEffectOfUnusualItems,annualTaxRateForCalcs,annualNormalizedEBITDA,annualNormali...
2026-06-20 17:32:25 - yfinance:data.py:_make_request:399 - DEBUG - params=None
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb()
2026-06-20 17:32:25 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_cookie_basic()
2026-06-20 17:32:25 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_cookie_basic()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_crumb_basic()
2026-06-20 17:32:25 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_crumb_basic()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb()
2026-06-20 17:32:25 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _make_request()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting get()
2026-06-20 17:32:25 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting _fetch_time_series()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG - Entering _fetch_time_series()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering get()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _make_request()
2026-06-20 17:32:26 - yfinance:data.py:_make_request:396 - DEBUG - url=https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/ABBNN.MX?symbol=ABBNN.MX&type=annualTreasurySharesNumber,annualPreferredSharesNumber,annualOrdinarySharesNumber,annual...
2026-06-20 17:32:26 - yfinance:data.py:_make_request:399 - DEBUG - params=None
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb()
2026-06-20 17:32:26 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_cookie_basic()
2026-06-20 17:32:26 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_cookie_basic()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_crumb_basic()
2026-06-20 17:32:26 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_crumb_basic()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb()
2026-06-20 17:32:26 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _make_request()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting get()
2026-06-20 17:32:26 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting _fetch_time_series()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG - Entering _fetch_time_series()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering get()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _make_request()
2026-06-20 17:32:27 - yfinance:data.py:_make_request:396 - DEBUG - url=https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/ABBNN.MX?symbol=ABBNN.MX&type=annualForeignSales,annualDomesticSales,annualAdjustedGeographySegmentData,annualFreeCash...
2026-06-20 17:32:27 - yfinance:data.py:_make_request:399 - DEBUG - params=None
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb()
2026-06-20 17:32:27 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_cookie_basic()
2026-06-20 17:32:27 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_cookie_basic()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_crumb_basic()
2026-06-20 17:32:27 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_crumb_basic()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb()
2026-06-20 17:32:27 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _make_request()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting get()
2026-06-20 17:32:27 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting _fetch_time_series()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG - Entering _fetch_time_series()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering get()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _make_request()
2026-06-20 17:32:28 - yfinance:data.py:_make_request:396 - DEBUG - url=https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/ABBNN.MX?symbol=ABBNN.MX&type=trailingTaxEffectOfUnusualItems,trailingTaxRateForCalcs,trailingNormalizedEBITDA,trailin...
2026-06-20 17:32:28 - yfinance:data.py:_make_request:399 - DEBUG - params=None
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering _get_cookie_and_crumb()
2026-06-20 17:32:28 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_cookie_basic()
2026-06-20 17:32:28 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_cookie_basic()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_crumb_basic()
2026-06-20 17:32:28 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_crumb_basic()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting _get_cookie_and_crumb()
2026-06-20 17:32:28 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting _make_request()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting get()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting _fetch_time_series()
2026-06-20 17:32:28 - yfinance:utils.py:wrapper:92 - DEBUG - Entering _fetch_time_series()
2026-06-20 17:32:29 - yfinance:utils.py:wrapper:92 - DEBUG - Entering _fetch_time_series()
2026-06-20 17:32:29 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering get()
2026-06-20 17:32:29 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering _make_request()
2026-06-20 17:32:29 - yfinance:data.py:_make_request:396 - DEBUG - url=https://query2.finance.yahoo.com/ws/fundamentals-timeseries/v1/finance/timeseries/ABBNN.MX?symbol=ABBNN.MX&type=trailingForeignSales,trailingDomesticSales,trailingAdjustedGeographySegmentData,trailing...
2026-06-20 17:32:29 - yfinance:data.py:_make_request:399 - DEBUG - params=None

In [4]:
from utils import create_text_file
company = "ABB LTD"
        
for r in rows:
    if  r['name'] == company:
        dump = r['row']
        sym = r['YSymbol']
        if len(sym) == 0:
            sym = r['symbol']
        print(f"{company} {sym} {dump}")
        filename = re.sub(r"[^A-Z0-9().]", "_", f"{company} ({sym})")
        create_text_file(folder_path="./dump/", filename=filename, content=dump)

ABB LTD ABBNN.MX {'maxAge': 86400, 'priceHint': 2, 'previousClose': 1808.57, 'open': 0.0, 'dayLow': 1808.57, 'dayHigh': 1808.57, 'regularMarketPreviousClose': 1808.57, 'regularMarketOpen': 0.0, 'regularMarketDayLow': 1808.57, 'regularMarketDayHigh': 1808.57, 'trailingPE': 39.21444, 'volume': 0, 'regularMarketVolume': 0, 'averageVolume': 61, 'averageVolume10days': 0, 'averageDailyVolume10Day': 0, 'bid': 0.0, 'ask': 0.0, 'marketCap': 3282467028992, 'nonDilutedMarketCap': 3409632913309, 'fiftyTwoWeekLow': 989.58, 'fiftyTwoWeekHigh': 1808.57, 'allTimeHigh': 1808.57, 'allTimeLow': 989.58, 'fiftyDayAverage': 1712.603, 'twoHundredDayAverage': 1457.5043, 'trailingAnnualDividendRate': 1.185, 'trailingAnnualDividendYield': 0.0006552138, 'currency': 'MXN', 'tradeable': False, 'quoteType': 'EQUITY', 'currentPrice': 1808.57, 'recommendationKey': 'none', 'financialCurrency': 'USD', 'symbol': 'ABBNN.MX', 'language': 'en-US', 'region': 'US', 'typeDisp': 'Equity', 'triggerable': False, 'customPriceAlertConfidence': 'LOW', 'hasPrePostMarketData': False, 'firstTradeDateMilliseconds': 1725975000000, 'regularMarketChange': 0.0, 'regularMarketDayRange': '1808.57 - 1808.57', 'fullExchangeName': 'Mexico', 'averageDailyVolume3Month': 61, 'fiftyTwoWeekLowChange': 818.9899, 'fiftyTwoWeekLowChangePercent': 0.82761365, 'fiftyTwoWeekRange': '989.58 - 1808.57', 'fiftyTwoWeekHighChange': 0.0, 'fiftyTwoWeekHighChangePercent': 0.0, 'fiftyTwoWeekChangePercent': 82.76137, 'marketState': 'CLOSED', 'regularMarketChangePercent': 0.0, 'regularMarketPrice': 1808.57, 'corporateActions': [], 'regularMarketTime': 1779378818, 'exchange': 'MEX', 'messageBoardId': 'finmb_18527', 'exchangeTimezoneName': 'America/Mexico_City', 'exchangeTimezoneShortName': 'CST', 'gmtOffSetMilliseconds': -21600000, 'market': 'mx_market', 'esgPopulated': False, 'shortName': 'ABB LTD', 'earningsTimestamp': 1784232000, 'earningsTimestampStart': 1784232000, 'earningsTimestampEnd': 1784232000, 'earningsCallTimestampStart': 1776844800, 'earningsCallTimestampEnd': 1776844800, 'isEarningsDateEstimate': False, 'epsTrailingTwelveMonths': 46.12, 'sharesOutstanding': 1814951722, 'impliedSharesOutstanding': 1814951722, 'bookValue': 141.7718, 'fiftyDayAverageChange': 95.96692, 'fiftyDayAverageChangePercent': 0.056035705, 'twoHundredDayAverageChange': 351.06567, 'twoHundredDayAverageChangePercent': 0.24086767, 'priceToBook': 12.756908, 'sourceInterval': 20, 'exchangeDataDelayedBy': 20, 'cryptoTradeable': False, 'trailingPegRatio': 3.2375}

Income Statement CSV:
,2021-12-31,2022-12-31,2023-12-31,2024-12-31,2025-12-31,2026-03-31
TaxEffectOfUnusualItems,,-94329000.0,29445000.0,-13129798.903108,48384000.0,46800000.0
TaxRateForCalcs,,0.223,0.195,0.243144,0.252,0.24375
NormalizedEBITDA,,4761000000.0,5682000000.0,5812000000.0,6926000000.0,7255000000.0
TotalUnusualItems,,-423000000.0,151000000.0,-54000000.0,192000000.0,192000000.0
TotalUnusualItemsExcludingGoodwill,,-423000000.0,151000000.0,-54000000.0,192000000.0,192000000.0
NetIncomeFromContinuingOperationNetMinorityInterest,,2518000000.0,3769000000.0,3709000000.0,4560000000.0,4863000000.0
ReconciledDepreciation,,814000000.0,780000000.0,761000000.0,813000000.0,837000000.0
ReconciledCostOfRevenue,,19736000000.0,21021000000.0,18582000000.0,19580000000.0,20614000000.0
EBITDA,,4338000000.0,5833000000.0,5758000000.0,7118000000.0,7447000000.0
EBIT,,3524000000.0,5053000000.0,4997000000.0,6305000000.0,6610000000.0
NetInterestIncome,,-58000000.0,-110000000.0,132000000.0,117000000.0,126000000.0
InterestExpense,,130000000.0,275000000.0,74000000.0,86000000.0,72000000.0
InterestIncome,,72000000.0,165000000.0,206000000.0,203000000.0,198000000.0
NormalizedIncome,,2846671000.0,3647445000.0,3749870201.096892,4416384000.0,4717800000.0
NetIncomeFromContinuingAndDiscontinuedOperation,,2475000000.0,3745000000.0,3935000000.0,4734000000.0,4956000000.0
TotalExpenses,,26034000000.0,27881000000.0,25830000000.0,27491000000.0,28696000000.0
TotalOperatingIncomeAsReported,,3337000000.0,4871000000.0,4735000000.0,6047000000.0,6353000000.0
DilutedAverageShares,,1910000000.0,1867000000.0,1851000000.0,1831000000.0,1826000000.0
BasicAverageShares,,1899000000.0,1855000000.0,1844000000.0,1827000000.0,1822250000.0
DilutedEPS,,1.3,2.01,2.13,2.59,2.72
BasicEPS,,1.3,2.02,2.13,2.59,2.72
DilutedNIAvailtoComStockholders,,2475000000.0,3745000000.0,3935000000.0,4734000000.0,4956000000.0
NetIncomeCommonStockholders,,2475000000.0,3745000000.0,3935000000.0,4734000000.0,4956000000.0
OtherunderPreferredStockDividend,,0.0,0.0,0.0,0.0,0.0
NetIncome,,2475000000.0,3745000000.0,3935000000.0,4734000000.0,4956000000.0
MinorityInterests,,-119000000.0,-79000000.0,-17000000.0,-89000000.0,-82000000.0
NetIncomeIncludingNoncontrollingInterests,,2594000000.0,3824000000.0,3952000000.0,4823000000.0,5038000000.0
NetIncomeDiscontinuousOperations,,-43000000.0,-24000000.0,226000000.0,174000000.0,93000000.0
NetIncomeContinuousOperations,,2637000000.0,3848000000.0,3726000000.0,4649000000.0,4945000000.0
TaxProvision,,757000000.0,930000000.0,1197000000.0,1570000000.0,1593000000.0
PretaxIncome,,3394000000.0,4778000000.0,4923000000.0,6219000000.0,6538000000.0
OtherIncomeExpense,2798000000.0,40000000.0,534000000.0,,,
OtherNonOperatingIncomeExpenses,,565000000.0,399000000.0,92000000.0,181000000.0,344000000.0
SpecialIncomeCharges,,-475000000.0,148000000.0,38000000.0,209000000.0,
GainOnSaleOfPPE,38000000.0,84000000.0,116000000.0,,,
GainOnSaleOfBusiness,2193000000.0,36000000.0,101000000.0,,,
OtherSpecialCharges,,193000000.0,-217000000.0,-117000000.0,-242000000.0,
WriteOff,,55000000.0,49000000.0,26000000.0,7000000.0,
ImpairmentOfCapitalAssets,33000000.0,55000000.0,49000000.0,27000000.0,,
RestructuringAndMergernAcquisition,,227000000.0,20000000.0,53000000.0,26000000.0,
EarningsFromEquityInterest,-100000000.0,-102000000.0,-16000000.0,,,
GainOnSaleOfSecurity,108000000.0,52000000.0,3000000.0,,,
NetNonOperatingInterestIncomeExpense,,-58000000.0,-110000000.0,132000000.0,117000000.0,126000000.0
InterestExpenseNonOperating,,130000000.0,275000000.0,74000000.0,86000000.0,72000000.0
InterestIncomeNonOperating,,72000000.0,165000000.0,206000000.0,203000000.0,198000000.0
OperatingIncome,,3412000000.0,4354000000.0,4753000000.0,5729000000.0,5876000000.0
OperatingExpense,,6298000000.0,6860000000.0,7248000000.0,7911000000.0,8082000000.0
OtherOperatingExpenses,-262000000.0,-278000000.0,,,,
ResearchAndDevelopment,,1166000000.0,1317000000.0,1268000000.0,1318000000.0,1348000000.0
SellingGeneralAndAdministration,,5132000000.0,5543000000.0,5980000000.0,6593000000.0,6734000000.0
SellingAndMarketingExpense,3281000000.0,3248000000.0,3415000000.0,3554000000.0,,
GeneralAndAdministrativeExpense,,1884000000.0,2128000000.0,5980000000.0,6593000000.0,6734000000.0
OtherGandA,1881000000.0,1884000000.0,2128000000.0,,,
GrossProfit,,9710000000.0,11214000000.0,12001000000.0,13640000000.0,13958000000.0
CostOfRevenue,,19736000000.0,21021000000.0,18582000000.0,19580000000.0,20614000000.0
TotalRevenue,,29446000000.0,32235000000.0,30583000000.0,33220000000.0,34572000000.0
OperatingRevenue,,29446000000.0,32235000000.0,30583000000.0,33220000000.0,34572000000.0


Balance CSV:
,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
TreasurySharesNumber,25757777.0,22422600.0,40495329.0,99741744.0,
OrdinarySharesNumber,1818141427.0,1838192288.0,1841507246.0,1865003331.0,
ShareIssued,1843899204.0,1860614888.0,1882002575.0,1964745075.0,
NetDebt,3664000000.0,2614000000.0,3937000000.0,3522000000.0,
TotalDebt,9090000000.0,7708000000.0,8743000000.0,8549000000.0,
TangibleBookValue,5331000000.0,4619000000.0,1626000000.0,860000000.0,
InvestedCapital,24391000000.0,21359000000.0,21238000000.0,20455000000.0,
WorkingCapital,9157000000.0,6105000000.0,3273000000.0,3041000000.0,
NetTangibleAssets,5331000000.0,4619000000.0,1626000000.0,860000000.0,
CapitalLeaseObligations,786000000.0,768000000.0,915000000.0,871000000.0,
CommonStockEquity,16087000000.0,14419000000.0,13410000000.0,12777000000.0,
TotalCapitalization,23916000000.0,21067000000.0,18631000000.0,17920000000.0,
TotalEquityGrossMinorityInterest,16646000000.0,14991000000.0,14146000000.0,13272000000.0,
MinorityInterest,559000000.0,572000000.0,736000000.0,495000000.0,
StockholdersEquity,16087000000.0,14419000000.0,13410000000.0,12777000000.0,
GainsLossesNotAffectingRetainedEarnings,,,-5070000000.0,-4556000000.0,-4088000000.0
OtherEquityAdjustments,,,-5070000000.0,-4556000000.0,-4088000000.0
TreasuryStock,1490000000.0,1091000000.0,1414000000.0,3061000000.0,
RetainedEarnings,22606000000.0,20648000000.0,19724000000.0,20082000000.0,
AdditionalPaidInCapital,64000000.0,50000000.0,7000000.0,141000000.0,
CapitalStock,160000000.0,162000000.0,163000000.0,171000000.0,
CommonStock,160000000.0,162000000.0,163000000.0,171000000.0,
TotalLiabilitiesNetMinorityInterest,28239000000.0,25297000000.0,26794000000.0,25876000000.0,
TotalNonCurrentLiabilitiesNetMinorityInterest,11818000000.0,10643000000.0,8790000000.0,9347000000.0,
OtherNonCurrentLiabilities,233000000.0,251000000.0,329000000.0,384000000.0,
LiabilitiesHeldforSaleNonCurrent,13000000.0,194000000.0,,20000000.0,43000000.0
DerivativeProductLiabilities,155000000.0,276000000.0,246000000.0,367000000.0,
EmployeeBenefits,,,686000000.0,719000000.0,1084000000.0
NonCurrentPensionAndOtherPostretirementBenefitPlans,550000000.0,541000000.0,686000000.0,719000000.0,
TradeandOtherPayablesNonCurrent,903000000.0,847000000.0,813000000.0,1287000000.0,
NonCurrentDeferredLiabilities,,,669000000.0,729000000.0,759000000.0
NonCurrentDeferredRevenue,,,,92000000.0,74000000.0
NonCurrentDeferredTaxesLiabilities,792000000.0,651000000.0,669000000.0,729000000.0,
LongTermDebtAndCapitalLeaseObligation,8362000000.0,7191000000.0,5887000000.0,5794000000.0,
LongTermCapitalLeaseObligation,533000000.0,543000000.0,666000000.0,651000000.0,
LongTermDebt,7829000000.0,6648000000.0,5221000000.0,5143000000.0,
LongTermProvisions,810000000.0,692000000.0,160000000.0,67000000.0,
CurrentLiabilities,16421000000.0,14654000000.0,18004000000.0,16529000000.0,
OtherCurrentLiabilities,,114000000.0,,262000000.0,
CurrentDeferredLiabilities,,,2844000000.0,2216000000.0,1989000000.0
CurrentDeferredRevenue,,,2844000000.0,2216000000.0,1989000000.0
CurrentDebtAndCapitalLeaseObligation,728000000.0,517000000.0,2856000000.0,2755000000.0,
CurrentCapitalLeaseObligation,253000000.0,225000000.0,249000000.0,220000000.0,
CurrentDebt,475000000.0,292000000.0,2607000000.0,2535000000.0,
OtherCurrentBorrowings,,,2607000000.0,2535000000.0,1384000000.0
PensionandOtherPostRetirementBenefitPlansCurrent,1712000000.0,1526000000.0,1566000000.0,1490000000.0,
CurrentProvisions,1477000000.0,1462000000.0,2411000000.0,2199000000.0,
PayablesAndAccruedExpenses,,,7913000000.0,7486000000.0,7359000000.0
CurrentAccruedExpenses,,,1407000000.0,1225000000.0,1118000000.0
InterestPayable,,,105000000.0,38000000.0,28000000.0
Payables,6797000000.0,6228000000.0,6611000000.0,6299000000.0,
OtherPayable,670000000.0,676000000.0,736000000.0,719000000.0,
TotalTaxPayable,917000000.0,871000000.0,1028000000.0,676000000.0,
IncomeTaxPayable,,,668000000.0,391000000.0,378000000.0
AccountsPayable,5210000000.0,4681000000.0,4847000000.0,4904000000.0,
TotalAssets,44885000000.0,40288000000.0,40940000000.0,39148000000.0,
TotalNonCurrentAssets,19307000000.0,19529000000.0,19663000000.0,19578000000.0,
OtherNonCurrentAssets,560000000.0,484000000.0,496000000.0,467000000.0,
DefinedPensionBenefit,937000000.0,688000000.0,780000000.0,916000000.0,
NonCurrentDeferredAssets,,,1381000000.0,1396000000.0,1177000000.0
NonCurrentDeferredTaxesAssets,1248000000.0,1299000000.0,1381000000.0,1396000000.0,
InvestmentsAndAdvances,,,187000000.0,130000000.0,1670000000.0
LongTermEquityInvestment,349000000.0,351000000.0,187000000.0,130000000.0,
GoodwillAndOtherIntangibleAssets,10756000000.0,9800000000.0,11784000000.0,11917000000.0,
OtherIntangibleAssets,1119000000.0,999000000.0,1223000000.0,1406000000.0,
Goodwill,9637000000.0,8801000000.0,10561000000.0,10511000000.0,
NetPPE,5457000000.0,4738000000.0,5035000000.0,4752000000.0,
AccumulatedDepreciation,-6620000000.0,-5818000000.0,-6236000000.0,-5792000000.0,
GrossPPE,12077000000.0,10556000000.0,11271000000.0,10544000000.0,
ConstructionInProgress,780000000.0,658000000.0,713000000.0,586000000.0,
OtherProperties,875000000.0,859000000.0,893000000.0,841000000.0,
MachineryFurnitureEquipment,6256000000.0,5393000000.0,5847000000.0,5495000000.0,
BuildingsAndImprovements,220000000.0,216000000.0,,,
LandAndImprovements,3946000000.0,3430000000.0,,,
Properties,0.0,0.0,3818000000.0,3622000000.0,
CurrentAssets,25578000000.0,20759000000.0,21277000000.0,19570000000.0,
OtherCurrentAssets,627000000.0,511000000.0,520000000.0,601000000.0,
AssetsHeldForSaleCurrent,3562000000.0,1154000000.0,,96000000.0,136000000.0
RestrictedCash,,15000000.0,18000000.0,18000000.0,30000000.0
PrepaidAssets,474000000.0,515000000.0,235000000.0,230000000.0,
Inventory,5669000000.0,5187000000.0,6149000000.0,6028000000.0,
FinishedGoods,1986000000.0,1819000000.0,2092000000.0,2036000000.0,
WorkInProcess,1228000000.0,1133000000.0,1284000000.0,1189000000.0,
RawMaterials,2455000000.0,2235000000.0,2773000000.0,2803000000.0,
Receivables,,,8536000000.0,7812000000.0,7541000000.0
ReceivablesAdjustmentsAllowances,,,-307000000.0,-308000000.0,-339000000.0
OtherReceivables,1463000000.0,1178000000.0,1429000000.0,1334000000.0,
AccountsReceivable,7162000000.0,6554000000.0,7107000000.0,6478000000.0,
CashCashEquivalentsAndShortTermInvestments,6621000000.0,5660000000.0,5819000000.0,4881000000.0,
OtherShortTermInvestments,1981000000.0,1334000000.0,1928000000.0,725000000.0,
CashAndCashEquivalents,4640000000.0,4326000000.0,3891000000.0,4156000000.0,
CashEquivalents,3242000000.0,2998000000.0,,,
CashFinancial,1398000000.0,1328000000.0,,,


Cashflow CSV:
,2021-12-31,2022-12-31,2023-12-31,2024-12-31,2025-12-31,2026-03-31
FreeCashFlow,,525000000.0,3520000000.0,3876000000.0,4468000000.0,4815000000.0
RepaymentOfDebt,,-2703000000.0,-1567000000.0,-2485000000.0,-433000000.0,-456000000.0
IssuanceOfDebt,,3849000000.0,2586000000.0,1914000000.0,1083000000.0,811000000.0
IssuanceOfCapitalStock,,610000000.0,482000000.0,451000000.0,99000000.0,
CapitalExpenditure,,-762000000.0,-770000000.0,-799000000.0,-1001000000.0,-999000000.0
InterestPaidSupplementalData,132000000.0,90000000.0,250000000.0,,,
IncomeTaxPaidSupplementalData,1292000000.0,1188000000.0,1147000000.0,,,
EndCashPosition,,4174000000.0,3909000000.0,4326000000.0,4640000000.0,3294000000.0
BeginningCashPosition,,4489000000.0,4174000000.0,3909000000.0,4326000000.0,4494000000.0
EffectOfExchangeRateChanges,,-189000000.0,-43000000.0,-207000000.0,111000000.0,31000000.0
ChangesInCash,,-126000000.0,-222000000.0,624000000.0,203000000.0,-1200000000.0
FinancingCashFlow,,-2394000000.0,-2897000000.0,-3326000000.0,-2877000000.0,-5131000000.0
CashFromDiscontinuedFinancingActivities,0.0,0.0,0.0,,,
CashFlowFromContinuingFinancingActivities,-4968000000.0,-2394000000.0,-2897000000.0,,,
NetOtherFinancingCharges,,-166000000.0,31000000.0,-72000000.0,-21000000.0,-34000000.0
CashDividendsPaid,,-1698000000.0,-1713000000.0,-1769000000.0,-1907000000.0,
CommonStockDividendPaid,,-1698000000.0,-1713000000.0,-1769000000.0,-1907000000.0,-3521000000.0
NetCommonStockIssuance,,-2943000000.0,-776000000.0,-796000000.0,-1400000000.0,-1359000000.0
CommonStockPayments,,-3553000000.0,-1258000000.0,-1247000000.0,-1499000000.0,-1458000000.0
CommonStockIssuance,,610000000.0,482000000.0,451000000.0,99000000.0,
NetIssuancePaymentsOfDebt,,2512000000.0,-346000000.0,-586000000.0,565000000.0,-103000000.0
NetShortTermDebtIssuance,,1366000000.0,-1365000000.0,-15000000.0,-85000000.0,-458000000.0
ShortTermDebtPayments,-83000000.0,,,,,
NetLongTermDebtIssuance,,1146000000.0,1019000000.0,-571000000.0,650000000.0,355000000.0
LongTermDebtPayments,,-2703000000.0,-1567000000.0,-2485000000.0,-433000000.0,-456000000.0
LongTermDebtIssuance,,3849000000.0,2586000000.0,1914000000.0,1083000000.0,811000000.0
InvestingCashFlow,,981000000.0,-1615000000.0,-725000000.0,-2389000000.0,-1883000000.0
CashFromDiscontinuedInvestingActivities,-364000000.0,-226000000.0,-23000000.0,,,
CashFlowFromContinuingInvestingActivities,2671000000.0,1207000000.0,-1592000000.0,,,
NetOtherInvestingChanges,,-14000000.0,7000000.0,-77000000.0,-131000000.0,-149000000.0
NetInvestmentPurchaseAndSale,,283000000.0,-1307000000.0,694000000.0,-758000000.0,-986000000.0
SaleOfInvestment,,770000000.0,759000000.0,2257000000.0,589000000.0,348000000.0
PurchaseOfInvestment,,-487000000.0,-2066000000.0,-1563000000.0,-1347000000.0,-1334000000.0
NetBusinessPurchaseAndSale,,1027000000.0,305000000.0,-650000000.0,-693000000.0,-217000000.0
SaleOfBusiness,2958000000.0,1315000000.0,530000000.0,,59000000.0,10000000.0
PurchaseOfBusiness,,-288000000.0,-225000000.0,-650000000.0,-752000000.0,-227000000.0
NetIntangiblesPurchaseAndSale,,-69000000.0,,,,
PurchaseOfIntangibles,,-69000000.0,,,,
NetPPEPurchaseAndSale,,-635000000.0,-623000000.0,-692000000.0,-807000000.0,-531000000.0
SaleOfPPE,,127000000.0,147000000.0,107000000.0,194000000.0,468000000.0
PurchaseOfPPE,,-762000000.0,-770000000.0,-799000000.0,-1001000000.0,-999000000.0
OperatingCashFlow,,1287000000.0,4290000000.0,4675000000.0,5469000000.0,5814000000.0
CashFromDiscontinuedOperatingActivities,-8000000.0,-47000000.0,-11000000.0,,,
CashFlowFromContinuingOperatingActivities,3338000000.0,1334000000.0,4301000000.0,,,
ChangeInWorkingCapital,,-1698000000.0,-113000000.0,-119000000.0,197000000.0,347000000.0
ChangeInOtherWorkingCapital,108000000.0,216000000.0,389000000.0,,,
ChangeInOtherCurrentAssets,,276000000.0,188000000.0,26000000.0,29000000.0,25000000.0
ChangeInPayablesAndAccruedExpense,1113000000.0,531000000.0,148000000.0,,,
ChangeInAccruedExpense,,137000000.0,252000000.0,-4000000.0,119000000.0,73000000.0
ChangeInPayable,,369000000.0,-129000000.0,180000000.0,147000000.0,497000000.0
ChangeInAccountPayable,659000000.0,395000000.0,-106000000.0,,,
ChangeInInventory,,-1602000000.0,-3000000.0,-133000000.0,132000000.0,-51000000.0
ChangeInReceivables,,-811000000.0,-633000000.0,-147000000.0,-222000000.0,-271000000.0
ChangesInAccountReceivables,-142000000.0,-831000000.0,-661000000.0,,,
OtherNonCashItems,,66000000.0,158000000.0,268000000.0,58000000.0,111000000.0
UnrealizedGainLossOnInvestmentSecurities,-123000000.0,-33000000.0,-29000000.0,,,
AssetImpairmentCharge,0.0,0.0,,,,
DeferredTax,,-344000000.0,-28000000.0,1000000.0,108000000.0,92000000.0
DeferredIncomeTax,-289000000.0,-344000000.0,-25000000.0,,,
DepreciationAmortizationDepletion,893000000.0,814000000.0,780000000.0,,,
DepreciationAndAmortization,,814000000.0,780000000.0,761000000.0,813000000.0,837000000.0
AmortizationCashFlow,318000000.0,282000000.0,263000000.0,252000000.0,,
AmortizationOfIntangibles,318000000.0,282000000.0,263000000.0,,,
Depreciation,,532000000.0,517000000.0,761000000.0,813000000.0,837000000.0
OperatingGainsLosses,-2298000000.0,-123000000.0,-304000000.0,,,
PensionAndEmployeeBenefitExpense,,-125000000.0,-48000000.0,-93000000.0,-48000000.0,-43000000.0
EarningsLossesFromEquityInvestments,100000000.0,102000000.0,16000000.0,,,
GainLossOnInvestmentSecurities,,-55000000.0,-83000000.0,15000000.0,-332000000.0,-191000000.0
GainLossOnSaleOfPPE,,-84000000.0,-116000000.0,-60000000.0,-198000000.0,-457000000.0
GainLossOnSaleOfBusiness,,17000000.0,-100000000.0,-57000000.0,3000000.0,12000000.0
NetIncomeFromContinuingOperations,,2594000000.0,3824000000.0,3726000000.0,4649000000.0,4945000000.0
RepurchaseOfCapitalStock,,,,,,-1458000000.0



2026-06-20 17:32:59 - root:utils.py:create_text_file:243 - DEBUG - File created successfully at: ./dump/ABB_LTD_(ABBNN.MX).txt

In [5]:
from screener import build_csv
ddf = df.clone()

print(ddf.sort(['country', 'name', 'VOL10DUSD'], descending=True)[['country', 'name', 'symbol', 'VOL10DUSD']].to_dicts())

columns = [
    "symbol", "isin", "name", "sector", "industry", "country",  "qscore",  "qscorePerf", "MKTCAP", "REVPS5YGR", 
    "MARGIN5YR", "Focf2Rev_AAvg5", "ratings_CURR", "ratings_1WA", "VE/EBITDA", "VE/CA", "CAPI/TANG", "PER", "Rendement", "Dette nette / EBITDA", 
    "Ratio courant", "VE/FCF", "%M200D", "closePrice", "quoteCurrency", "En Solde", "Juste Prix", "NPRICE", "L%H", "priceCurrency", "reportCurrency", 
    "EV2FCF_CurTTM", "EV", "TTMFCF", "Net Income", "NPMTRENDGR", "Dette nette", "shrOutstanding", "EBITDA", "PR1DAYPRC", "PR5DAYPRC", "ChPctPriceMTD", 
    "ChPctPrice5Y", "YSymbol", "businessSummary", "AROE5YAVG", "YLD+PRY", "PDATE", "qMKTCAP.USD", "VOL10DAVG", "EPSTRENDGR", "EnSolde2", 'DCF', 'TTMFCFSHR', 
    'FOCF_AYr5CAGR', "MKTCAP.USD", "VOL10DUSD", "TTMROAPCT", "TTMROEPCT", "roic", 'SctRoic', 'momentum'
]
#locale.setlocale(locale.LC_NUMERIC, os.getenv("LANG", "C"))  # force point as decimal sign since build_csv will use locale configuration
build_csv(ddf, None, None, columns, "screener4.csv", ";", "%.1f", 40)


columns = [ 
    "YSymbol", "sector", "country", "name", "industry", "qscore", "qscorePerf", "EPSTRENDGR", "EnSolde2", 
    "%M200D", "ChPctPrice5Y", "Rendement", "roic", "momentum"
]
crit = (
    ("qscorePerf", "QSP", 50),      # score loic + perf
    ("roic", "ROIC", 10),           # return on invested capital
    ("EnSolde2", "SLD", 10),        # en solde de x%   DCF FCFF (discounted cash flow from free cash flow to the firm)
    ("VOL10DUSD", "VOL", 1e6),      # daily traded volume in US dollar
    #("momentum", "momentum", 10),   # momentum (accélération à la hausse) acceptable
)
# Removing banks, freight, holdings and mines
critRemoveRegex = (
    ("sector", r"(?i)Financial", "industry", r"(?i)bank|investment|Financial|insurance"),
    ("sector", r"(?i)Basic Materials", "industry", r"(?i)Mining"),
    ("sector", r"(?i)Transportation", "industry", r"(?i)Freight|Tankers"),
    ("name", r"(?i)holding"),
)

tmpdf = build_csv(ddf, crit, critRemoveRegex, None, None, ";", "%.1f", 40).sort(by=["qscorePerf", "EnSolde2"], descending=[True, True]).head(15)
display(tmpdf[["country", "YSymbol", "name", "EnSolde2", "MKTCAP", "MKTCAP.USD", "NPRICE", "VOL10DAVG", "VOL10DUSD", "momentum"]])

# List of Yahoo! tickers
tmpdf = tmpdf[["YSymbol", "name", "EnSolde2", "MKTCAP.USD"]]
tickers = tmpdf["YSymbol"].to_list()
print("tickers", tickers)
names = tmpdf["name"].to_list()

# List of market caps (in USD), needed by PyPortfolioOpt
mcaps = tmpdf[["name", "MKTCAP.USD"]].rows_by_key(key=["name"], unique=True)
mcaps = {k: v[0] for k, v in mcaps.items()}

# Upside, according to discounted cash flow
viewdict = tmpdf[["name", "EnSolde2"]].rows_by_key(key=["name"], unique=True)
viewdict = {k: v[0]/100.0 for k, v in viewdict.items()}

print("upside", viewdict)
print("market cap pct", mcaps)

[{'country': None, 'name': 'QUANTA SERVICES', 'symbol': 'PWR.MX', 'VOL10DUSD': 6468}, {'country': None, 'name': 'ABB LTD', 'symbol': 'ABBNN.MX', 'VOL10DUSD': -104}, {'country': 'Mexico', 'name': 'WAL-MART DE MEXICO, S.A.B. DE C.V.', 'symbol': 'WALMEX.MX', 'VOL10DUSD': 100888234}, {'country': 'Mexico', 'name': 'GRUPO MEXICO, S.A.B. DE C.V.', 'symbol': 'GMEXICOB.MX', 'VOL10DUSD': 68462386}, {'country': 'Mexico', 'name': 'AMERICA MOVIL, S.A.B. DE C.V.', 'symbol': 'AMXB.MX', 'VOL10DUSD': 86028980}]
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column Juste Prix in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column PR5DAYPRC in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column isin in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column ChPctPriceMTD in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column En Solde in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column PDATE in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column PR1DAYPRC in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column AROE5YAVG in csv
2026-06-20 17:32:59 - root:screener.py:build_csv:1113 - DEBUG - adding empty column ratings_1WA in csv

shape: (0, 10)
┌─────────┬─────────┬──────┬──────────┬────────┬────────────┬────────┬───────────┬───────────┬──────────┐
│ country ┆ YSymbol ┆ name ┆ EnSolde2 ┆ MKTCAP ┆ MKTCAP.USD ┆ NPRICE ┆ VOL10DAVG ┆ VOL10DUSD ┆ momentum │
│ ---     ┆ ---     ┆ ---  ┆      --- ┆    --- ┆        --- ┆    --- ┆       --- ┆       --- ┆      --- │
│ str     ┆ str     ┆ str  ┆      f64 ┆    i64 ┆        i64 ┆    f64 ┆       i64 ┆       i64 ┆       i8 │
╞═════════╪═════════╪══════╪══════════╪════════╪════════════╪════════╪═══════════╪═══════════╪══════════╡
└─────────┴─────────┴──────┴──────────┴────────┴────────────┴────────┴───────────┴───────────┴──────────┘

tickers []
upside {}
market cap pct {}

In [6]:
import yfinance as yf

# downloading prices for 7 years + SPY as standard performance
ohlc = yf.download(tickers+["SPY"], period="7y")
if ohlc is not None:
    prices = ohlc["Close"]
    prices = prices.ffill().bfill()
    prices[prices.isna().any(axis=1)].index
    market_prices = prices[["SPY"]]
    prices = prices[tickers]

    prices = prices.rename(columns=dict(zip(tickers, names)))

    display(prices.tail())  # our portfolio
    display(market_prices.tail())  # SPY

2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG - Entering download()
2026-06-20 17:32:59 - yfinance:multi.py:download:105 - DEBUG - Disabling multithreading because DEBUG logging enabled
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -  Entering history()
2026-06-20 17:32:59 - peewee:peewee.py:execute_sql:3303 - DEBUG - ('SELECT "t1"."key", "t1"."value" FROM "_tz_kv" AS "t1" WHERE ("t1"."key" = ?) LIMIT ? OFFSET ?', ['SPY', 1, 0])
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -   Entering history()
2026-06-20 17:32:59 - yfinance:history.py:history:193 - DEBUG - SPY: Yahoo GET parameters: {'range': '7y', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -    Entering get()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -     Entering _make_request()
2026-06-20 17:32:59 - yfinance:data.py:_make_request:398 - DEBUG - url=https://query2.finance.yahoo.com/v8/finance/chart/SPY
2026-06-20 17:32:59 - yfinance:data.py:_make_request:399 - DEBUG - params={'range': '7y', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -      Entering _get_cookie_and_crumb()
2026-06-20 17:32:59 - yfinance:data.py:_get_cookie_and_crumb:354 - DEBUG - cookie_mode = 'basic'
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -       Entering _get_cookie_and_crumb_basic()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -        Entering _get_cookie_basic()
2026-06-20 17:32:59 - yfinance:data.py:_get_cookie_basic:190 - DEBUG - reusing cookie
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -        Exiting _get_cookie_basic()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:92 - DEBUG -        Entering _get_crumb_basic()
2026-06-20 17:32:59 - yfinance:data.py:_get_crumb_basic:214 - DEBUG - reusing crumb
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -        Exiting _get_crumb_basic()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -       Exiting _get_cookie_and_crumb_basic()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -      Exiting _get_cookie_and_crumb()
2026-06-20 17:32:59 - yfinance:data.py:_make_request:437 - DEBUG - response code=200
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -     Exiting _make_request()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -    Exiting get()
2026-06-20 17:32:59 - yfinance:history.py:history:307 - DEBUG - SPY: yfinance received OHLC data: 2019-06-19 13:30:00 -> 2026-06-18 13:30:00
2026-06-20 17:32:59 - yfinance:history.py:history:339 - DEBUG - SPY: OHLC after cleaning: 2019-06-19 09:30:00-04:00 -> 2026-06-18 09:30:00-04:00
2026-06-20 17:32:59 - yfinance:history.py:history:427 - DEBUG - SPY: OHLC after combining events: 2019-06-19 00:00:00-04:00 -> 2026-06-18 00:00:00-04:00
2026-06-20 17:32:59 - yfinance:history.py:history:510 - DEBUG - SPY: yfinance returning OHLC: 2019-06-19 00:00:00-04:00 -> 2026-06-18 00:00:00-04:00
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -   Exiting history()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG -  Exiting history()
2026-06-20 17:32:59 - yfinance:utils.py:wrapper:97 - DEBUG - Exiting download()

Empty DataFrame
Columns: []
Index: [2026-06-12 00:00:00, 2026-06-15 00:00:00, 2026-06-16 00:00:00, 2026-06-17 00:00:00, 2026-06-18 00:00:00]

Ticker             SPY
Date
2026-06-12  739.843994
2026-06-15  752.890381
2026-06-16  748.401978
2026-06-17  739.056030
2026-06-18  746.739990

In [7]:
from pypfopt import black_litterman, risk_models


# See Black-Litterman allocation example in https://github.com/PyPortfolio/PyPortfolioOpt

S = risk_models.CovarianceShrinkage(prices).ledoit_wolf()
# plotting.plot_covariance(S, plot_correlation=True)

delta = black_litterman.market_implied_risk_aversion(market_prices)

market_prior = black_litterman.market_implied_prior_returns(mcaps, delta, S)
# market_prior.plot.barh(figsize=(10,5))

ValueError: Found array with 0 sample(s) (shape=(0, 0)) while a minimum of 1 is required by LedoitWolf.

In [ ]:
from pypfopt import BlackLittermanModel
from collections import OrderedDict
import pandas as pd
import seaborn as sns



bl = BlackLittermanModel(S, pi=market_prior, absolute_views=viewdict, omega="default")
bl.bl_weights(delta)
weights = dict(bl.clean_weights())
weights = {k: v for k, v in weights.items() if v >= 0.01}
print("Portfolio weights:", weights)
bl.portfolio_performance(verbose=True, risk_free_rate=0.045)

# optimized allocation for the expected performance
# Sort by values
sorted_weights = OrderedDict(sorted(weights.items(), key=lambda item: -item[1]))
colors = sns.color_palette("tab20", n_colors=len(sorted_weights)+1)
print(len(sorted_weights))
pd.Series(sorted_weights).plot.pie(autopct='%1.1f%%', figsize=(10, 10), wedgeprops={"edgecolor": "black", "linewidth": 1}, colors=colors)